#!/bin/bash

FLAGS_GREP='-s -n -h'

if [[ "$1" ]]
then
PATH_FILES='$*'
else
PATH_FILES='.'
fi

## READ FILE ONE BY ONE

find $PATH_FILES -name "*.c" | 
while read FILE
do

## PRINT NAME OF THE CURRENT FILE
  echo "$FILE"

## BAD RETURN

  grep $FLAGS_GREP -v -E '\s+return\s*\(.+\)\s*;' $FILE | grep -v -E '\s+return\s*;' | grep -E '\s+return.*' | grep -v -E ':\s*\*\*' | grep -v -E ':\s*\/\*' | grep -v -E ':\s*\/\/' |
while read LINE
do
  echo -n "line "
  LINE=`echo -n "$LINE" | sed -e 's/:/\t/g' | cut -f 1`
  echo -e "$LINE\t: Bad return"
done

## END OF READ FILE
done
